---
# The service for internal components communication with the configstore.
apiVersion: v1
kind: Service
metadata:
  name: agola-configstore
spec:
  ports:
    - port: 4002
  selector:
    app: agola
    component: configstore
