---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agola-runservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agola
      component: runservice
  template:
    metadata:
      labels:
        app: agola
        component: runservice
    spec:
      containers:
        - name: agola
          image: sorintlab/agola:v0.9.0
          command:
            - /bin/agola
            - serve
            - "--config"
            - /mnt/agola/config/config.yml
            - "--components"
            - runservice
          env:
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: config-volume
              mountPath: /mnt/agola/config
            - name: agola-localdata
              mountPath: /mnt/agola/local
      volumes:
        - name: config-volume
          configMap:
            name: agola
        - name: agola-localdata
          emptyDir: {}
