---
# The service for internal components communication with the runservice.
apiVersion: v1
kind: Service
metadata:
  name: agola-runservice
spec:
  ports:
    - port: 4000
  selector:
    app: agola
    component: runservice
