---
apiVersion: v1
kind: Secret
metadata:
  name: &cluster_name patroni
  labels:
    application: patroni
    cluster-name: *cluster_name
type: Opaque
data:
  superuser-password: emFsYW5kbw==
  replication-password: cmVwLXBhc3M=
