---
apiVersion: v1
kind: Service
metadata:
  name: &cluster_name patroni
  labels:
    application: patroni
    cluster-name: *cluster_name
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
